const a = 10 % 2;
console.log(a);
const b = 9 % 2;
console.log(b);
const c = 7 % 2;
console.log(c);
const d = 10 % 17;
console.log(d);
const e = 0 % 1;
console.log("e : ", e);
const f = 1 % 0;
console.log("f ...: ", f);
