const arr = [1, 2, 3];
const arr2 = [...arr, 4];
console.log(arr2);
console.log("---------------------");
console.log(Array.from({ length: 10 }, () => 0));
console.log("---------------------");
let arr4 = [2, 3, 1];
arr4 = arr;
console.log(arr4);
if (1) console.log("과연");
